<a href="https://colab.research.google.com/github/M-A-Lopa/CSE330/blob/main/CSE330_Lab_01_Examimport_numpy_as_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy.polynomial import Polynomial

Task 1

In [ ]:
#A
p = Polynomial([-5.0625, 10, 0, 2.25, 0, -0.25])
val = p(8)
print(val)
#B
p_prime = p.deriv(1)
p_prime_two = p_prime.deriv(1)

x = 3
denominator = (p_prime_two(3))**2
func = (p(3) + p_prime(3)) / denominator
print(round(func, 5))

-6965.0625
-0.00062


Task 2

In [ ]:
def X_vondo(x):
  n = len(x)
  thunder = np.zeros((n, n))

  for i in range(n):
    power = 1
    for j in range(n//2):
      thunder[i][j] = (x[i])**power
      power += 2
      row = j

  for i in range(n):
    power = 0
    for k in range(row+1, n):
      thunder[i][k] = x[i]**power
      power+= 2
  return thunder

data_x = np.array([2,3,4,6])
print(X_vondo(data_x))

[[  2.   8.   1.   4.]
 [  3.  27.   1.   9.]
 [  4.  64.   1.  16.]
 [  6. 216.   1.  36.]]


Task 3

In [ ]:
def dh(f, x, h):
  return ((f(x) - f(x-h)) / (h))

def dh_1(f, x, h):
   return ((4*dh(f, x, h/2) - dh(f, x, h))/ 3)

def dh_2(f, x, h):
  return ((16*dh_1(f, x, h/2) - dh_1(f, x, h))/ 15)

def richardson_extrapolation_numpy(f, x, h):
  diff_dh = dh_2(f, x, h)
  return diff_dh

f = Polynomial([10, 2, -1.5, 4, -2, 3])
x = 3
h = 0.1
D2 = richardson_extrapolation_numpy(f, x, h)
D2_rounded = np.round(D2, 3)
print(D2_rounded)

1088.544
